- name: Gather full system info
  setup:

- name: Get OS distribution
  setup:
    filter: ansible_distribution

- name: Get IPv4 addresses
  setup:
    filter: ansible_all_ipv4_addresses

- name: Check disk space
  command: df -h

- name: List files in /etc
  command: ls -l /etc

- name: Get hostname
  command: hostname

- name: Download a webpage
  get_url:
    url: https://www.google.com
    dest: /tmp/google.html
    mode: '0644'

- name: Set custom MOTD message
  lineinfile:
    path: /etc/motd
    line: "Welcome to ITgenius DevOps"
    create: yes

